Test solution
mate-academy/py-cache-decorator pull request #1134
Opened 2024-05-18 13:01 UTC by VasylRysan

2024-05-18 13:56 UTC, vsmutok requested changes

2024-05-18 13:56 UTC, vsmutok commented on app/main.py
> +
use `functools.wraps`

2024-05-18 13:56 UTC, vsmutok commented on app/main.py
> +            return storage.get(args)
what if two different functions have the same `args` but different `kwargs`?
you must use `args` + `kwargs` as the keys of `storage `

2024-05-18 13:56 UTC, vsmutok requested changes
.

2024-05-19 12:19 UTC, vasylhnatiuk approved these changes

2025-04-02 06:01 UTC, closed without merging