Task 4
mate-academy/py-cache-decorator pull request #1218
Opened 2024-07-23 13:03 UTC by Poznanskyi

2024-07-23 15:32 UTC, Oleksl888 requested changes

2024-07-23 15:32 UTC, Oleksl888 commented on app/main.py
> +            return result
Can you simplify this so you have only one return statement?

2024-07-23 15:32 UTC, Oleksl888 commented on app/main.py
> +@cache
Examples shouldn't be included, please remove

2024-07-25 02:40 UTC, MNDonut approved these changes

2025-02-18 20:42 UTC, closed without merging