Develop
mate-academy/py-cache-decorator pull request #1309
Opened 2024-09-24 19:42 UTC by YuriiZosia

2024-09-24 19:48 UTC, vasylhnatiuk requested changes
use only one return in wrapper()

2024-09-24 19:48 UTC, vasylhnatiuk commented on app/main.py
> +    # Словник для зберігання результатів, - наш Кеш,
delete useless comments, use docstring instead of it

2024-09-25 05:25 UTC, vsmutok requested changes

2024-09-25 05:25 UTC, vsmutok commented on app/main.py
> +            result = cache_dict[args]
1. use `functools.wraps`
2. you should check both `args` and `kwargs` because the function might accept the same `args` but different `kwargs`.

2024-09-25 13:44 UTC, vasylhnatiuk approved these changes

2024-09-26 16:57 UTC, closed without merging