Decorator solution
mate-academy/py-cache-decorator pull request #1316
Opened 2024-09-27 14:24 UTC by molodsh1y1

2024-09-27 14:59 UTC, 94nj111 requested changes

2024-09-27 14:59 UTC, 94nj111 commented on app/main.py
> +
I think one return is enough here

2024-09-27 14:59 UTC, 94nj111 commented on app/main.py
> +    wrapper.cache_storage = cache_storage
looks unnecessary

2024-09-27 17:28 UTC, 94nj111 approved these changes
lgtm!

2024-09-30 06:30 UTC, AnyoneClown approved these changes
Good job!

2026-01-08 21:35 UTC, closed without merging