Solution
mate-academy/py-cache-decorator pull request #31
Opened 2022-05-08 08:27 UTC by MarkoKhodan

2022-05-11 10:22 UTC, IvanRamyk requested changes

2022-05-11 10:22 UTC, IvanRamyk commented on app/main.py
> +            return func(*args)
You calculate the function result a second time here (the first time is in the 14th line). 
Use the stored result in the `cache_dict`

2022-05-24 12:51 UTC, Abnormaltype requested changes

2022-05-24 12:51 UTC, Abnormaltype commented on app/main.py
> +            cache_dict.update({key: func(*args)})
```suggestion
            cache_dict.update({key: func(*args, **kwargs)})
```

2022-05-24 12:51 UTC, Abnormaltype commented on app/main.py
> +        key = f"{func.__name__}{args}"
You don't actually need to remember or check the function name

2022-05-24 13:10 UTC, Abnormaltype requested changes

2022-05-24 13:21 UTC, Abnormaltype approved these changes
Good job!

2025-06-05 06:10 UTC, closed without merging