solution
mate-academy/py-cache-decorator pull request #436
Opened 2023-03-16 13:07 UTC by goldenuni

2023-03-16 13:34 UTC, ArsenPidhoretskyi requested changes

2023-03-16 13:34 UTC, ArsenPidhoretskyi commented on app/main.py
> +        key = str(args) + str(kwargs)
Why you need to convert to str? Remove this in function will only enter *args

2023-03-16 13:34 UTC, ArsenPidhoretskyi commented on app/main.py
> +        memory[key] = value
Write inline this

2023-03-17 08:40 UTC, Bohdan-Salamakha requested changes
don't work on the master branch - bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

2024-03-22 10:29 UTC, closed without merging