'Solution'
mate-academy/py-cache-decorator pull request #498
Opened 2023-05-21 17:28 UTC by mwellick

2023-05-21 17:57 UTC, Bohdan-Salamakha requested changes

2023-05-21 17:57 UTC, Bohdan-Salamakha commented on app/main.py
> +def cache(func: Callable) -> Any:
return type is Callable

2023-05-22 10:23 UTC, Bohdan-Salamakha requested changes

2023-05-22 10:23 UTC, Bohdan-Salamakha commented on app/main.py
> +    def wrapper(*args) -> Callable:
return type isn't Callable

2023-05-22 17:58 UTC, EdAlekseiev approved these changes
Good job

2024-02-22 09:22 UTC, closed without merging