Solution
mate-academy/py-cache-decorator pull request #534
Opened 2023-05-28 17:36 UTC by OlhaTryhub

2023-05-29 09:18 UTC, LiudmylaKulinchenko requested changes

2023-05-29 09:18 UTC, LiudmylaKulinchenko commented on app/main.py
> +        if (*args,) in results_dict:
The `args` parameter already represents a tuple of arguments, so there is no need to pack it into another tuple `(*args,) `

2023-05-29 12:17 UTC, Oleg-s-s approved these changes
Good job)

2023-06-02 14:59 UTC, closed without merging

2023-06-02 15:04 UTC, LiudmylaKulinchenko approved these changes
🌺