implemented cache decorator
mate-academy/py-cache-decorator pull request #572
Opened 2023-06-25 09:28 UTC by BGBroth

2023-06-25 10:01 UTC, Polyakiv-Andrey requested changes

2023-06-25 10:01 UTC, Polyakiv-Andrey commented on app/main.py
> +    def inner(*args) -> int:
you lose the metadata of the function being wrapped (its name, etc.)

2023-06-27 12:24 UTC, Abnormaltype requested changes

2023-06-27 12:24 UTC, Abnormaltype commented on app/main.py
> +            cache_dict[func] = {}
unnecessary if, you don't need it

2023-06-27 12:24 UTC, Abnormaltype commented on app/main.py
> +        else:
unnecessary `else`

2023-06-27 17:38 UTC, Polyakiv-Andrey approved these changes
Good job!

2024-07-09 09:30 UTC, closed without merging