Implemented cache decorator!
mate-academy/py-cache-decorator pull request #630
Opened 2023-08-06 08:51 UTC by raychw

2023-08-06 13:45 UTC, Polyakiv-Andrey requested changes

2023-08-06 13:45 UTC, Polyakiv-Andrey commented on app/main.py
> +    def wrapper(*args) -> Callable:
The video tutorials talked about a tool that allows you not to lose the name of the decorated function and its docstring. This tool is in the functools library.

2023-08-14 07:35 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-08-14 07:35 UTC, Dimosphen1 commented on app/main.py
> +        key = args
Do not assign one variable to another, you can operate with `args` directly.

2023-08-14 07:35 UTC, Dimosphen1 commented on app/main.py
> +        else:
There is no need for the `else` statement, code will not execute after `return`.

2023-08-14 07:35 UTC, Dimosphen1 commented on app/main.py
> +            cached_results[key] = result
There is no need for a `result` variable, write function output to the cache directly.

2023-08-14 07:35 UTC, Dimosphen1 commented on app/main.py
> +from functools import wraps
You should perform imports in alphabetical order here.

2023-08-14 07:35 UTC, Dimosphen1 commented on app/main.py
> +    def wrapper(*args) -> Callable:
The return type of `wrapper` can be any, because you return the result of calculations, not the function itself.

2023-08-14 13:03 UTC, Polyakiv-Andrey approved these changes
Good job!

2024-07-18 09:43 UTC, closed without merging