Completed
mate-academy/py-cache-decorator pull request #875
Opened 2023-12-20 16:00 UTC by Bombardier256

2023-12-20 17:01 UTC, Bombardier256 reviewed
a, b, c have been replaced by alfa, bravo, coco in order to pass the test

2023-12-20 18:25 UTC, vsmutok requested changes

2023-12-20 18:25 UTC, vsmutok commented on app/main.py
> +    return [number ** power for number in n_tuple]
remove from PR

2023-12-20 18:25 UTC, vsmutok commented on app/main.py
> +    def inner(*args, **kwargs) -> dict:
add functools.wraps

2023-12-20 19:02 UTC, Bombardier256 commented
Functions have been removed and functools.wraps added

2023-12-22 09:24 UTC, ArsenPidhoretskyi approved these changes
Well done!

2024-07-03 12:51 UTC, closed without merging